# Generated by Django 6.1 on 2026-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=150)),
                ('produto', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=100, null=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fila', models.CharField(choices=[('espera', 'Espera'), ('executando', 'Executando'), ('pronto', 'Pronto'), ('entregue', 'Entregue')], default='espera', max_length=20)),
                ('pagamento', models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pendente', 'Pendente')], default='pendente', max_length=30)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
