# Generated by Django 6.1 on 2026-09-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaofilamento', '0003_venda_valor_esperado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='lucro_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
